# Generated by Django 4.1.7 on 2023-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosis', 'verbose_name_plural': 'Diagnoses'},
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms',
            field=models.ManyToManyField(related_name='diagnoses', to='core.symptom'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, null=True, to='core.diagnosis'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.ManyToManyField(to='core.symptom'),
        ),
    ]
