# Generated by Django 4.1.7 on 2023-05-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_diagnosis_options_diagnosis_symptoms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='symptoms',
        ),
    ]
