# Generated by Django 4.1.7 on 2023-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_user_is_admin_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[['Fungal infection', 'Disease 1'], ['Allergy', 'Disease 2'], ['GERD', 'Disease 3'], ['Chronic cholestasis', 'Disease 4'], ['Drug Reaction', 'Disease 5'], ['Peptic ulcer diseae', 'Disease 6'], ['AIDS', 'Disease 7'], ['Diabetes', 'Disease 8'], ['Gastroenteritis', 'Disease 9'], ['Bronchial Asthma', 'Disease 10'], ['Hypertension', 'Disease 11'], [' Migraine', 'Disease 12'], ['Cervical spondylosis', 'Disease 13'], ['Paralysis (brain hemorrhage)', 'Disease 14'], ['Jaundice', 'Disease 15'], ['Malaria', 'Disease 16'], ['Chicken pox', 'Disease 17'], ['Dengue', 'Disease 18'], ['Typhoid', 'Disease 19'], ['hepatitis A', 'Disease 20'], ['Hepatitis B', 'Disease 21'], ['Hepatitis C', 'Disease 22'], ['Hepatitis D', 'Disease 23'], ['Hepatitis E', 'Disease 24'], ['Alcoholic hepatitis', 'Disease 25'], ['Tuberculosis', 'Disease 26'], ['Common Cold', 'Disease 27'], ['Pneumonia', 'Disease 28'], ['Dimorphic hemmorhoids(piles)', 'Disease 29'], ['Heartattack', 'Disease 30'], ['Varicoseveins', 'Disease 31'], ['Hypothyroidism', 'Disease 32'], ['Hyperthyroidism', 'Disease 33'], ['Hypoglycemia', 'Disease 34'], ['Osteoarthristis', 'Disease 35'], ['Arthritis', 'Disease 36'], ['(vertigo) Paroymsal  Positional Vertigo', 'Disease 37'], ['Acne', 'Disease 38'], ['Urinary tract infection', 'Disease 39'], ['Psoriasis', 'Disease 40'], ['Impetigo', 'Disease 41']], help_text='Category', max_length=50),
        ),
    ]
