# Generated by Django 4.1.7 on 2023-05-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
