# Generated by Django 4.1.7 on 2023-05-31 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_appointment'),
        ('user_app', '0015_alter_doctor_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='category',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ManyToManyField(blank=True, null=True, to='core.diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.doctor')),
                ('symptoms', models.ManyToManyField(to='core.symptom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.ManyToManyField(to='core.diagnosis'),
        ),
    ]
